variables:
  VITE_APP_VERSION: $CI_COMMIT_SHORT_SHA

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths: 
      - build/



ecs_deploy:
 stage: deploy
 image: 
  name: amazon/aws-cli:2.23.0
  entrypoint: [""] #by default after installation, docker writes aws but we have aws --version in the script so gitlab would write aws aws --version and this command will give an error. therefore we type this which says gitlab should initially write nothing and execute our script.
 script:
   - aws --version
   - aws ecs register-task-definition --cli-input-json file://aws/td_prod.json
   - aws ecs update-service --cluster LearnGitlabApp-Cluster-Prod --service LearnGitlabApp-Service-Prod --task-definition LearnGitlabAppTo-Prod
   - aws ecs wait services-stable --cluster LearnGitlabAppCluster-Prod --services LearnGitlabApp-Service-Prod