variables:
  NETLIFY_SITE_ID: '5cf5db69-9828-4ea0-bffd-a8e3b39340da'
  VITE_APP_VERSION: $CI_COMMIT_SHORT_SHA

stages:
  - build
  - deploy
  - .pre

build_docker_netlify:
  stage: .pre
  image: docker:27
  services:
    - docker:27-dind #docker daemon
  script: 
    - docker --version
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/netlify:18.0.0 -f Dockerfile .
    - docker image ls
    - docker push $CI_REGISTRY_IMAGE/netlify:18.0.0



build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths: 
      - build/

netlify_prod:
  image: $CI_REGISTRY_IMAGE/netlify:18.0.0
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  environment: production
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --prod --dir build