stages:
  - build
  - test
  - unit

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm ci #we write npm ci instead of npm install as now npm will install the exact same packages and 
             #dependencies which are written in the lock-package.json file.
    - npm run build
  artifacts:
    paths:
      - build/

test_website:
  image: alpine
  stage: test
  script:
    - test -f build/index.html 

unit_tests:
  image: node:22-alpine
  stage: unit
  script:
    - npm ci
    - npm test
